version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform and Ansible..."
      - yum install -y unzip wget ansible
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version

      - terraform --version
      - ansible --version

  pre_build:
    commands:
      - echo "Downloading dynamic tfvars from S3..."
      - aws s3 cp s3://splunk-deployment-test/$TFVARS_S3_KEY terraform.tfvars
      - echo "Pre-build phase complete."

  build:
    commands:
      - terraform init
      - chmod +x scripts/check_key.sh
      - terraform apply -auto-approve
      - echo "Waiting for EC2 SSH to be ready..."
      - echo "Running Ansible Playbook..."
      - ansible-playbook -i inventory.ini playbooks/master_playbook.yml --ssh-common-args='-o StrictHostKeyChecking=no'

  post_build:
    commands:
      - echo "EC2 Splunk + Ansible Deployment Completed Successfully!"